server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: order80
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/