server:
  port: 8003

spring:
  application:
    name: cloud-payment-service-zk
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mcip:3306/study?useUnicode=true&characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: mcip:2391,mcip:2392,mcip:2393

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.springcloud.entities
